
function logAnimate(){$('.form').animate({height:"toggle",opacity:"toggle"},1000,'linear');var name=document.getElementById("head").innerHTML;if(name=="Log In"){name="Register";setTimeout(()=>{username.focus();},900);}else{name="Log In";setTimeout(()=>{userSIEmail.focus();},900);}
document.getElementById("head").innerText=name;}
$('.message a').click(function(){resetForm();logAnimate();});$('#form_button').click(function(){$('#form_button').fadeOut("slow",function(){$("#container").fadeIn();TweenMax.from("#container",.2,{scale:0,ease:Sine.easeInOut});TweenMax.to("#container",.2,{scale:1,ease:Sine.easeInOut});userSIEmail.focus();});});$(".close-btn").click(function(){resetForm();TweenMax.from("#container",.4,{scale:1,ease:Sine.easeInOut});TweenMax.to("#container",.4,{left:"0px",scale:0,ease:Sine.easeInOut});$("#container").fadeOut(800,function(){$("#form_button").fadeIn(800);});});var username=document.getElementById("userFullName");var email=document.getElementById("userEmail");var password=document.getElementById("userPassword");var password_confirm=document.getElementById("userPassword-confirm");var userSIEmail=document.getElementById("userSIEmail");var userSIPassword=document.getElementById("userSIPassword");var email_err=document.getElementById('email_err');var password_err=document.getElementById('password_err');var name_error=document.getElementById('name_error');var email_error=document.getElementById('email_error');var password_error=document.getElementById('password_error');var allInputs=[username,email,password,password_confirm,userSIEmail,userSIPassword];var checkSIEmail=true;var checkSIEmailPattern=true;var checkSIPass=true;var checkSIPassPattern=true;var checkName=true;var checkNameLen=true;var checkMail=true;var checkMailPattern=true;var checkPass=true;var checkPassPattern=true;var checkPassConfirm=true;function addElementMulti(el,s,fn){el.forEach(e=>e.addEventListener(s,fn,true));}
function addElementEventMulti(el,s,fn){el.forEach(l=>{s.split(' ').forEach(e=>{l.addEventListener(e,fn,true)});});}
function blurAll(){allInputs.forEach(e=>{verifyAll(e);});}
function resetForm(){document.getElementById("form-signUP").reset();document.getElementById("form").reset();blurAll();}
function showPassLog(){(userSIPassword.type==="password")?userSIPassword.type="text":userSIPassword.type="password";}
function showPassSI(){(password.type==="password")?password.type="text":password.type="password";(password_confirm.type==="password")?password_confirm.type="text":password_confirm.type="password";}
allInputs.forEach(e=>{if(e){addElementEventMulti([userSIEmail,userSIPassword],"input focus",ValidateLog);addElementEventMulti([username,email,password,password_confirm],"input focus",Validate);addElementMulti(allInputs,"blur",()=>{blurAll();},true);}});function searchKeyPress(e){e=e||window.event;if(e.keyCode==13){var name=document.getElementById("head").innerHTML;if(name=="Log In"){document.getElementById('login').click();return false;}else if(name=="Register"){document.getElementById('signup').click();return false;}}
return true;}
function Validate(){checkName=(username.value.trim()=="");checkNameLen=(username.value.trim().length<3);checkMail=(email.value.trim()=="");checkMailPattern=(!email.value.match(email.pattern));checkPass=(password.value.trim()=="");checkPassPattern=(!password.value.match(password.pattern));checkPassConfirm=(password.value.trim()!=password_confirm.value);var nextElement;if(username===document.activeElement){nextElement=validationAll(this);if(checkName){nextElement.textContent="Username is required";return false;}else if(checkNameLen){nextElement.textContent="Username must be at least 3 characters";return false;}else{verifyValidate(username);}}else if(email===document.activeElement){nextElement=validationAll(this);if(checkMail){nextElement.textContent="Email is required";return false;}else if(checkMailPattern){nextElement.textContent="Email Syntax is wrong";return false;}else{verifyValidate(email);}}else if(password===document.activeElement){nextElement=validationAll(this);if(checkPass){nextElement.textContent="Password is required";return false;}else if(checkPassPattern){nextElement.textContent="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters";return false;}else{verifyValidate(password);}}else if(password_confirm===document.activeElement){nextElement=validationAll(this);if(checkPassConfirm){password.style.border="1px solid red";nextElement.textContent="The two passwords do not match";return false;}
else{password.style.border="1px solid #5e6e66";verifyValidate(password_confirm);}}}
function ValidateLog(){checkSIEmail=(userSIEmail.value.trim()==="");checkSIEmailPattern=(!userSIEmail.value.match(userSIEmail.pattern));checkSIPass=(userSIPassword.value.trim()=="");checkSIPassPattern=(!userSIPassword.value.match(userSIPassword.pattern));var nextElement;if(userSIEmail===document.activeElement){nextElement=validationAll(this);if(checkSIEmail){nextElement.textContent="Email is required";return false;}else if(checkSIEmailPattern){nextElement.textContent="Email Syntax is wrong";return false;}else{verifyValidate(userSIEmail);}}else if(userSIPassword===document.activeElement){nextElement=validationAll(this);if(checkSIPass){nextElement.textContent="Password is required";return false;}else if(checkSIPassPattern){nextElement.textContent="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters";return false;}else{verifyValidate(userSIPassword);}}}
function validationAll(input){input.style.border="1px solid red";input.parentElement.style.color="red";input.focus();return input.parentElement.children[1];}
function verifyAll(input){if(input.value==""){input.style.border="1px solid #5e6e66";input.parentElement.style.color="#5e6e66";input.parentElement.children[1].innerHTML="";return true;}}
function verifyValidate(input){if(input.value!=""){input.style.border="1px solid #5e6e66";input.parentElement.style.color="#5e6e66";input.parentElement.children[1].innerHTML="";return true;}}
function signUp(){var userFullName=username.value.trim();console.log(userFullName);var userEmail=email.value.trim();var userPassword=password.value.trim();if(checkName||checkNameLen){username.focus();}else if(checkMailPattern||checkMail){email.focus();}else if(checkPass||checkPassPattern){password.focus();}else if(checkPassConfirm){password_confirm.focus();}
else{firebase.auth().createUserWithEmailAndPassword(userEmail,userPassword).then((success)=>{var user=firebase.auth().currentUser;var uid;if(user!=null){uid=user.uid;}
var firebaseRef=firebase.database().ref();var userData={userFullName:userFullName,userEmail:userEmail,userPassword:userPassword,headerStyle:'rgba(255, 255, 255, 0.4)',bodyStyle1:'rgb(255, 255, 255)',bodyStyle2:'#f9f9f9',primaryStyle:'#0c65ed',checkDark:true}
firebaseRef.child(uid).set(userData);swal('Your Account Created','Your account was created successfully, you can log in now.',).then((value)=>{setTimeout(function(){logAnimate();resetForm();},1000)});}).catch((error)=>{var errorCode=error.code;var errorMessage=error.message;resetForm();swal({type:'error',title:errorCode,text:errorMessage})});}}
function signIn(){var SIEmail=userSIEmail.value.trim();var SIPassword=userSIPassword.value.trim();if(checkSIEmail||checkSIEmailPattern){document.getElementById("userSIEmail").focus();}else if(checkSIPass||checkSIPassPattern){document.getElementById("userSIPassword").focus();}
else{firebase.auth().signInWithEmailAndPassword(SIEmail,SIPassword).then((success)=>{swal('successfull','Succesfully signed in',).then((value)=>{setTimeout(function(){window.location.replace("index.html");resetForm();},1000)});}).catch((error)=>{var errorCode=error.code;var errorMessage=error.message;swal({type:'error',title:errorCode,text:errorMessage})});}}
$('.sign_out').on('click',signOut);$(this).data('clicked',true);function signOut(){firebase.auth().signOut().then(function(){swal({icon:'success',title:'successfull',text:'signed out',showConfirmButton:false}).then((value)=>{setTimeout(function(){window.location.replace("form.html");},1000)});}).catch(function(error){let errorMessage=error.message;swal({type:'error',title:'Error',text:errorMessage})});}